### PR TITLE
Fix Execution failed for task ':app:validateSigningDebug'.

### PR DESCRIPTION
**Pull request by EvgenyTerebenin**
fix Execution failed for task ':app:validateSigningDebug'. Keystore file '.../hms-push-clientdemo-android/app/xx.xx' not found for signing config 'config'.

### CODE REVIEW

**Comment by HMSPushKit** [comment]
> fix Execution failed for task ':app:validateSigningDebug'. Keystore file '.../hms-push-clientdemo-android/app/xx.xx' not found for signing config 'config'.

Actually, you need to create your own keystore file , because the signingConfigs in the app's build.gradle is xxx.xx. We cannot provide the signingConfigs file in this project for secruity.

**Comment by EvgenyTerebenin** [comment]
> > fix Execution failed for task ':app:validateSigningDebug'. Keystore file '.../hms-push-clientdemo-android/app/xx.xx' not found for signing config 'config'.
> 
> Actually, you need to create your own keystore file , because the signingConfigs in the app's build.gradle is xxx.xx. We cannot provide the signingConfigs file in this project for secruity.

You can set lines commented by default

**Comment by HMSPushKit** [comment]
> > > fix Execution failed for task ':app:validateSigningDebug'. Keystore file '.../hms-push-clientdemo-android/app/xx.xx' not found for signing config 'config'.
> > 
> > 
> > Actually, you need to create your own keystore file , because the signingConfigs in the app's build.gradle is xxx.xx. We cannot provide the signingConfigs file in this project for secruity.
> 
> You can set lines commented by default

Thanks for your reminder, we will set lines commented ASAP.

**Comment by HMSPushKit** [comment]
I just change the file , and your pull request has conflicts, so i close this pull request first. You can bring up the new.

**Pull request closed without merging**
